import {AppProps} from "next/dist/shared/lib/router/router";
import '../styles/globals.css';
import Head from "next/head";

function MyApp({Component, pageProps}: AppProps): JSX.Element {
    return <>
        <Head>
            <title>My Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
            <link
                href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
                rel="stylesheet"/>
        </Head>
        <Component {...pageProps} />
    </>
}

export default MyApp
